export const DOMAIN_ERROR_CODES = [
  'ACCOUNT_NOT_FOUND',
  'ACCOUNT_ALREADY_EXISTS',
  'CURRENCY_ALREADY_EXISTS',
  'CURRENCY_NOT_REGISTERED',
  'INVALID_BILLING_PERIOD',
  'INVALID_MONEY_AMOUNT',
  'INVALID_DATE',
] as const;

export type DomainErrorCode = (typeof DOMAIN_ERROR_CODES)[number];
